### ISSUE TITLE
Network Enable all themes by default

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-cms#14]
Having to enable new themes in the Network Admin doesn't seem like it's really giving us anything useful. The use case so far as I can tell is for sites like WP.com.

Should we just enable all themes by default instead?

-----------

Acceptance criteria:

- [x] All themes are network enabled by default
- [x] A config option can be set to toggle this feature, defaults to on
- [x] Config option is documented

**Comment by joehoyle** [comment]
Yeah I was thinking this too

**Comment by roborourke** [comment]
That functionality is primarily geared towards networks where individuals have their own site & themes available but I think it's good to consider some of our client sites eg:

- one with a multisite, 3 distinct sites and a theme for each, one of those sites belongs to and is managed by a separate business unit within the larger organisation
- another with a large network of blogs, mostly on the same theme but a few with their own theme with customisations

Do we want the risk of someone switching theme by accident? Do we care if people have the option of switching to a theme they shouldn't? What permissions do we need to lock down? Is worth taking the control away from admins and giving it to network admins only?

Given that the default theme can be set, what about the option of moving this to configuration and hiding theme selection? Eg. `modules.cms.theme = twentynineteen`

I was thinking about an equivalent to the `environments` key for overriding config per environment. In a similar way we could have a `sites` section where the key has to match the host name to apply settings for.

**Comment by rmccue** [comment]
As it affects the network admin, I mean essentially changing the default to enabled, but still allowing themes to be disabled. (That should address @joemcgill's concern?)

I do like the idea of potentially rethinking the permissions entirely or moving it into source control instead, but I'd say we want to push that out for now. Potentially, at that point you actually want to move site definition entirely to the codebase too.

**Comment by joemcgill** [comment]
I'm fine with opt out instead of opt in for the default here. @roborourke already covered the use cases I was thinking of. Additionally, I imagine a future scenario where we have a client wanting to offer a turn-key solution to people in their organization for creating micro-sites (a common use case in education, where I previously worked) where the network admin would need control of what themes were available.

As long as it's configurable, auto-enabling all themes on the network is ok from my perspective, but for most of our projects I would definitely prefer to manage themes via code/configuration rather than in the database (via admin UI).
