### ISSUE TITLE
Meta tags do not appear on main post or category archive pages

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-cms#357]
Steps to reproduce:
1. On the front end, navigate to the blog page OR click on a category to navigate to the category archive page
2. In the browser inspector, view the page source and expand the `<head>` section.
3. The Altis Generator tag appears but no other meta tags/OG data.

Expected result:
Appropriate meta tags appear in the `<head>` per the test documentation

### Screenshots

Actual output:
![Screen Shot 2021-04-05 at 12 54 29 PM](https://user-images.githubusercontent.com/991511/113613973-1d965780-960f-11eb-9c14-88b134c43bd4.png)

Expected output:
![Screen Shot 2021-04-05 at 12 55 15 PM](https://user-images.githubusercontent.com/991511/113613986-20914800-960f-11eb-8fe6-eb608f609307.png)

Acceptance criteria:

- [ ] ...

**Comment by roborourke** [comment]
Turns out this is expected, they're just not implemented - in terms of opengraph tags at least there just isn't really a suitable representation of an "archive object" that needs special handling for sharing.

At the very least this isn't a bug and can be closed, but we could perhaps change it to an enhancement or spike to see if there's a suitable way to represent archive pages.

For reference these tags come from the https://github.com/humanmade/meta-tags plugin.

**Comment by jazzsequence** [comment]
Pretty sure other SEO plugins (notably Yoast) adds meta tags for archive pages with the data stored in the taxonomy. Can open an enhancement ticket on the Meta Tags repo.
