### ISSUE TITLE
Update Authorship plugin to use `capabilities` queries instead of `who`

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms#523]
Authorship plugin needs updating for WP 5.9's new capabilities user queries that replace the role based `who` query parameter:

https://make.wordpress.org/core/2022/01/05/new-capability-queries-in-wordpress-5-9/

**Comment by veselala** [comment]
@roborourke we've estimated this on 3 points and moved it to the backlog

**Comment by robindevitt** [comment]
From the [related post](https://make.wordpress.org/core/2022/01/05/new-capability-queries-in-wordpress-5-9/): 

>Making use of capability queries while retaining compatibility for older WordPress versions, one could use code as follows to support both:
```
$args = array(
    'orderby'    => 'post_count',
    'order'      => 'DESC',
    'capability' => array( 'edit_posts' ),
);
 
// Capability queries were only introduced in WP 5.9.
if ( version_compare( $GLOBALS['wp_version'], '5.9-alpha', '<' ) ) {
    $args['who'] = 'authors';
    unset( $args['capability'] );
}
 
$authors = get_users( $args );
```

Should we keep a fall back for older WordPress versions?

**Comment by roborourke** [comment]
We don't need to but I'd check with @johnbillion as to whether he has a pref. If the `who` part of the query in the plugin is hardcoded then we can likely keep backwards compatibility as you suggest. Will need to check guest author caps too.

**Comment by johnbillion** [comment]
I personally like to retain back compat for a couple of versions, but this isn't my project any more so I'm easy. The back compat code above is simple enough so we might as well implement it.

**Comment by shadyvb** [comment]
IIRC Authorship does _not_ work with either `who` or `capabilities`, it is actually the opposite, it needs to drop them rather than use them. So wherever we're checking and removing `who`, we should do the same for `capabilities`. The compat code above isn't reflective of what the plugin does. But I may have missed something 🤷 

These are the instances that we have using that param:
https://github.com/humanmade/authorship/blob/develop/inc/class-users-controller.php#L89
https://github.com/humanmade/authorship/blob/develop/inc/class-users-controller.php#L292

Seems straight-forward to give `capability` the same treatment as `who`.

**Comment by roborourke** [comment]
Yeah that's what @robindevitt ascertained so PR should be ready soon. Think it was a little confusing looking for instances of `'who'` because when you build the plugin locally you get a full checkout of roots WP in the tests directory so it looked like way more work than it was.

**Comment by robindevitt** [comment]
PR has been merged and closed
