### ISSUE TITLE
Add safe SVG plugin

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-cms#63]
SVGs are stripped from content in WP by default, this plugin sanitises and allows them https://wordpress.org/plugins/safe-svg/

**Comment by roborourke** [comment]
Or alternatively implement this library directly in the module https://github.com/darylldoyle/svg-sanitizer

**Comment by kadamwhite** [comment]
Got tripped up on this because Composer couldn't pick up the repositories field where I tried to specify a WPackagist dependency within `altis-media`; we'll need to fork or otherwise try to get this up on Packagist to proceed. I've PR'd a `composer.json` against the plugin's Git mirror, see [this PR](https://github.com/darylldoyle/safe-svg/pull/7) — if it ends up on composer that's in my opinion the best outcome by far.

**Comment by darylldoyle** [comment]
Hi 👋 

I've pushed Safe SVG up to Packigist now and re-tagged the `1.9.4` release with the composer bits, so you should be good to pull that. Packigist info is [here](https://packagist.org/packages/darylldoyle/safe-svg).

I hope the plugin works well for you!

**Comment by roborourke** [comment]
@darylldoyle very much appreciated - thanks! We should catch up if you're ever at a UK WordCamp or similar, we at least owe you a beer or 2

**Comment by joehoyle** [comment]
@kadamwhite does this need handing off, or are you still planning to include the plugin?

**Comment by roborourke** [comment]
@joehoyle I finished this off, all merged and sorted
